# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config

name: Dahua NVR
version: "1.0.2"
slug: dahua-nvr
description: Control cameras connected to Dahua NVR
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  dahua_host: 192.168.0.111
  dahua_username: admin
  dahua_password: admin
schema:
  dahua_host: str
  dahua_username: str
  dahua_password: password
services:
  - mqtt:need
